var simplemaps_worldmap_mapdata={
  main_settings: {
    width: "responsive",
    background_color: "#FFFFFF",
    background_transparent: "yes",
    border_color: "#ffffff",
    popups: "detect",
    state_description: "State description",
    state_color: "#dee6f3",
    state_hover_color: "#ffc0cb",
    state_url: "https://www.metliner.com/",
    border_size: "1",
    all_states_inactive: "no",
    all_states_zoomable: "no",
    location_description: "Location description",
    location_color: "#FF0067",
    location_opacity: 0.8,
    location_hover_opacity: 1,
    location_url: "",
    location_size: 25,
    location_type: "square",
    location_image_source: "frog.png",
    location_border_color: "#FFFFFF",
    location_border: 2,
    location_hover_border: 2.5,
    all_locations_inactive: "no",
    all_locations_hidden: "no",
    label_color: "#d5ddec",
    label_hover_color: "#d5ddec",
    label_size: 22,
    label_font: "Arial",
    hide_labels: "no",
    zoom: "yes",
    back_image: "no",
    initial_back: "no",
    initial_zoom: -1,
    initial_zoom_solo: "no",
    region_opacity: 1,
    region_hover_opacity: 0.6,
    zoom_out_incrementally: "yes",
    zoom_percentage: 0.99,
    zoom_time: 0.5,
    popup_color: "white",
    popup_opacity: 0.9,
    popup_shadow: 1,
    popup_corners: 5,
    popup_font: "12px/1.5 Verdana, Arial, Helvetica, sans-serif",
    popup_nocss: "no",
    div: "map",
    auto_load: "yes",
    url_new_tab: "yes",
    images_directory: "default",
    fade_time: 0.1,
    link_text: "View Website",
    state_image_url: "",
    state_image_position: "",
    location_image_url: ""
  },
  state_specific: {
    AF:{name:"Afghanistan",color:"#e9dcc9",description:"0 cities"},
    AO:{name:"Angola",color:"#cfbeb4",description:"0 cities"},
    AL:{name:"Albania",color:"#b1b6ba",description:"0 cities"},
    AE:{name:"United Arab Emirates",color:"#82ac7c",description:"1 city"},
    AR:{name:"Argentina",color:"#bfd2c6",description:"0 cities"},
    AM:{name:"Armenia",color:"#7297a0",description:"0 cities"},
    AU:{name:"Australia",color:"#8d9daf",description:"2 cities"},
    AT:{name:"Austria",color:"#b8d0cd",description:"1 city"},
    AZ:{name:"Azerbaijan",color:"#b48c8a",description:"0 cities"},
    BI:{name:"Burundi",color:"#d0b1a3",description:"0 cities"},
    BE:{name:"Belgium",color:"#a88c7d",description:"0 cities"},
    BJ:{name:"Benin",color:"#a493b7",description:"0 cities"},
    BF:{name:"Burkina Faso",color:"#a089a0",description:"0 cities"},
    BD:{name:"Bangladesh",color:"#6d6e80",description:"0 cities"},
    BG:{name:"Bulgaria",color:"#e9dcc9",description:"0 cities"},
    BH:{name:"Bahrain",color:"#cfbeb4",description:"0 cities"},
    BA:{name:"Bosnia and Herzegovina",color:"#b1b6ba",description:"0 cities"},
    BY:{name:"Belarus",color:"#82ac7c",description:"0 cities"},
    BZ:{name:"Belize",color:"#bfd2c6",description:"0 cities"},
    BO:{name:"Bolivia",color:"#7297a0",description:"0 cities"},
    BR:{name:"Brazil",color:"#8d9daf",description:"1 city"},
    BN:{name:"Brunei Darussalam",color:"#b8d0cd",description:"0 cities"},
    BT:{name:"Bhutan",color:"#b48c8a",description:"0 cities"},
    BW:{name:"Botswana",color:"#d0b1a3",description:"0 cities"},
    CF:{name:"Central African Republic",color:"#a88c7d",description:"0 cities"},
    CA:{name:"Canada",color:"#a493b7",description:"6 cities"},
    CH:{name:"Switzerland",color:"#a089a0",description:"0 cities"},
    CL:{name:"Chile",color:"#6d6e80",description:"0 cities"},
    CN:{name:"China",color:"#e9dcc9",description:"9 cities"},
    CI:{name:"Côte d'Ivoire",color:"#cfbeb4",description:"0 cities"},
    CM:{name:"Cameroon",color:"#b1b6ba",description:"0 cities"},
    CD:{name:"Democratic Republic of the Congo",color:"#82ac7c",description:"0 cities"},
    CG:{name:"Republic of Congo",color:"#bfd2c6",description:"0 cities"},
    CO:{name:"Colombia",color:"#7297a0",description:"0 cities"},
    CR:{name:"Costa Rica",color:"#8d9daf",description:"0 cities"},
    CU:{name:"Cuba",color:"#b8d0cd",description:"0 cities"},
    CZ:{name:"Czech Republic",color:"#b48c8a",description:"0 cities"},
    DE:{name:"Germany",color:"#d0b1a3",description:"1 city"},
    DJ:{name:"Djibouti",color:"#a88c7d",description:"0 cities"},
    DK:{name:"Denmark",color:"#a493b7",description:"1 city"},
    DO:{name:"Dominican Republic",color:"#a089a0",description:"0 cities"},
    DZ:{name:"Algeria",color:"#6d6e80",description:"0 cities"},
    EC:{name:"Ecuador",color:"#e9dcc9",description:"0 cities"},
    EG:{name:"Egypt",color:"#cfbeb4",description:"0 cities"},
    ER:{name:"Eritrea",color:"#b1b6ba",description:"0 cities"},
    EE:{name:"Estonia",color:"#82ac7c",description:"0 cities"},
    ET:{name:"Ethiopia",color:"#bfd2c6",description:"0 cities"},
    FI:{name:"Finland",color:"#7297a0",description:"0 cities"},
    FJ:{name:"Fiji",color:"#8d9daf",description:"0 cities"},
    GA:{name:"Gabon",color:"#b8d0cd",description:"0 cities"},
    GB:{name:"United Kingdom",color:"#b48c8a",description:"1 city"},
    GE:{name:"Georgia",color:"#d0b1a3",description:"0 cities"},
    GH:{name:"Ghana",color:"#a88c7d",description:"0 cities"},
    GN:{name:"Guinea",color:"#a493b7",description:"0 cities"},
    GM:{name:"The Gambia",color:"#a089a0",description:"0 cities"},
    GW:{name:"Guinea-Bissau",color:"#6d6e80",description:"0 cities"},
    GQ:{name:"Equatorial Guinea",color:"#e9dcc9",description:"0 cities"},
    GR:{name:"Greece",color:"#cfbeb4",description:"0 cities"},
    GL:{name:"Greenland",color:"#b1b6ba",description:"0 cities"},
    GT:{name:"Guatemala",color:"#82ac7c",description:"0 cities"},
    GY:{name:"Guyana",color:"#bfd2c6",description:"0 cities"},
    HN:{name:"Honduras",color:"#7297a0",description:"0 cities"},
    HR:{name:"Croatia",color:"#8d9daf",description:"0 cities"},
    HT:{name:"Haiti",color:"#b8d0cd",description:"0 cities"},
    HU:{name:"Hungary",color:"#b48c8a",description:"0 cities"},
    ID:{name:"Indonesia",color:"#d0b1a3",description:"1 city"},
    IN:{name:"India",color:"#a88c7d",description:"0 cities"},
    IE:{name:"Ireland",color:"#a493b7",description:"0 cities"},
    IR:{name:"Iran",color:"#a089a0",description:"0 cities"},
    IQ:{name:"Iraq",color:"#6d6e80",description:"0 cities"},
    IS:{name:"Iceland",color:"#e9dcc9",description:"0 cities"},
    IL:{name:"Israel",color:"#cfbeb4",description:"0 cities"},
    IT:{name:"Italy",color:"#b1b6ba",description:"0 cities"},
    JM:{name:"Jamaica",color:"#82ac7c",description:"0 cities"},
    JO:{name:"Jordan",color:"#bfd2c6",description:"0 cities"},
    JP:{name:"Japan",color:"#7297a0",description:"14 cities"},
    KZ:{name:"Kazakhstan",color:"#8d9daf",description:"0 cities"},
    KE:{name:"Kenya",color:"#b8d0cd",description:"0 cities"},
    KG:{name:"Kyrgyzstan",color:"#b48c8a",description:"0 cities"},
    KH:{name:"Cambodia",color:"#d0b1a3",description:"0 cities"},
    KR:{name:"Republic of Korea",color:"#a88c7d",description:"5 cities"},
    XK:{name:"Kosovo",color:"#a493b7",description:"0 cities"},
    KW:{name:"Kuwait",color:"#a089a0",description:"0 cities"},
    LA:{name:"Lao PDR",color:"#6d6e80",description:"0 cities"},
    LB:{name:"Lebanon",color:"#e9dcc9",description:"0 cities"},
    LR:{name:"Liberia",color:"#cfbeb4",description:"0 cities"},
    LY:{name:"Libya",color:"#b1b6ba",description:"0 cities"},
    LK:{name:"Sri Lanka",color:"#82ac7c",description:"0 cities"},
    LS:{name:"Lesotho",color:"#bfd2c6",description:"0 cities"},
    LT:{name:"Lithuania",color:"#7297a0",description:"0 cities"},
    LU:{name:"Luxembourg",color:"#8d9daf",description:"0 cities"},
    LV:{name:"Latvia",color:"#b8d0cd",description:"0 cities"},
    MA:{name:"Morocco",color:"#b48c8a",description:"0 cities"},
    MD:{name:"Moldova",color:"#d0b1a3",description:"0 cities"},
    MG:{name:"Madagascar",color:"#a88c7d",description:"0 cities"},
    MX:{name:"Mexico",color:"#a493b7",description:"1 city"},
    MK:{name:"Macedonia",color:"#a089a0",description:"0 cities"},
    ML:{name:"Mali",color:"#6d6e80",description:"0 cities"},
    MM:{name:"Myanmar",color:"#e9dcc9",description:"0 cities"},
    ME:{name:"Montenegro",color:"#cfbeb4",description:"0 cities"},
    MN:{name:"Mongolia",color:"#b1b6ba",description:"0 cities"},
    MZ:{name:"Mozambique",color:"#82ac7c",description:"0 cities"},
    MR:{name:"Mauritania",color:"#bfd2c6",description:"0 cities"},
    MW:{name:"Malawi",color:"#7297a0",description:"0 cities"},
    MY:{name:"Malaysia",color:"#8d9daf",description:"1 city"},
    NA:{name:"Namibia",color:"#b8d0cd",description:"0 cities"},
    NE:{name:"Niger",color:"#b48c8a",description:"0 cities"},
    NG:{name:"Nigeria",color:"#d0b1a3",description:"0 cities"},
    NI:{name:"Nicaragua",color:"#a88c7d",description:"0 cities"},
    NL:{name:"Netherlands",color:"#a493b7",description:"0 cities"},
    NO:{name:"Norway",color:"#a089a0",description:"0 cities"},
    NP:{name:"Nepal",color:"#6d6e80",description:"0 cities"},
    NZ:{name:"New Zealand",color:"#e9dcc9",description:"2 cities"},
    OM:{name:"Oman",color:"#cfbeb4",description:"0 cities"},
    PK:{name:"Pakistan",color:"#b1b6ba",description:"0 cities"},
    PA:{name:"Panama",color:"#82ac7c",description:"0 cities"},
    PE:{name:"Peru",color:"#bfd2c6",description:"0 cities"},
    PH:{name:"Philippines",color:"#7297a0",description:"1 city"},
    PG:{name:"Papua New Guinea",color:"#8d9daf",description:"0 cities"},
    PL:{name:"Poland",color:"#b8d0cd",description:"0 cities"},
    KP:{name:"Dem. Rep. Korea",color:"#b48c8a",description:"0 cities"},
    PT:{name:"Portugal",color:"#d0b1a3",description:"1 city"},
    PY:{name:"Paraguay",color:"#a88c7d",description:"0 cities"},
    PS:{name:"Palestine",color:"#a493b7",description:"0 cities"},
    QA:{name:"Qatar",color:"#a089a0",description:"1 city"},
    RO:{name:"Romania",color:"#6d6e80",description:"0 cities"},
    RU:{name:"Russia",color:"#e9dcc9",description:"1 city"},
    RW:{name:"Rwanda",color:"#cfbeb4",description:"0 cities"},
    EH:{name:"Western Sahara",color:"#b1b6ba",description:"0 cities"},
    SA:{name:"Saudi Arabia",color:"#82ac7c",description:"0 cities"},
    SD:{name:"Sudan",color:"#bfd2c6",description:"0 cities"},
    SS:{name:"South Sudan",color:"#7297a0",description:"0 cities"},
    SN:{name:"Senegal",color:"#8d9daf",description:"0 cities"},
    SL:{name:"Sierra Leone",color:"#b8d0cd",description:"0 cities"},
    SV:{name:"El Salvador",color:"#b48c8a",description:"0 cities"},
    RS:{name:"Serbia",color:"#d0b1a3",description:"0 cities"},
    SR:{name:"Suriname",color:"#a88c7d",description:"0 cities"},
    SK:{name:"Slovakia",color:"#a493b7",description:"1 city"},
    SI:{name:"Slovenia",color:"#a089a0",description:"0 cities"},
    SE:{name:"Sweden",color:"#6d6e80",description:"0 cities"},
    SZ:{name:"Eswatini",color:"#e9dcc9",description:"0 cities"},
    SY:{name:"Syria",color:"#cfbeb4",description:"0 cities"},
    TD:{name:"Chad",color:"#b1b6ba",description:"0 cities"},
    TG:{name:"Togo",color:"#82ac7c",description:"0 cities"},
    TH:{name:"Thailand",color:"#bfd2c6",description:"1 city"},
    TJ:{name:"Tajikistan",color:"#7297a0",description:"0 cities"},
    TM:{name:"Turkmenistan",color:"#8d9daf",description:"0 cities"},
    TL:{name:"Timor-Leste",color:"#b8d0cd",description:"0 cities"},
    TN:{name:"Tunisia",color:"#b48c8a",description:"0 cities"},
    TR:{name:"Turkey",color:"#d0b1a3",description:"1 city"},
    TW:{name:"Taiwan",color:"#a88c7d",description:"3 cities"},
    TZ:{name:"Tanzania",color:"#a493b7",description:"0 cities"},
    UG:{name:"Uganda",color:"#a089a0",description:"0 cities"},
    UA:{name:"Ukraine",color:"#6d6e80",description:"0 cities"},
    UY:{name:"Uruguay",color:"#e9dcc9",description:"0 cities"},
    US:{name:"United States",color:"#cfbeb4",description:"33 cities"},
    UZ:{name:"Uzbekistan",color:"#b1b6ba",description:"0 cities"},
    VE:{name:"Venezuela",color:"#82ac7c",description:"0 cities"},
    VN:{name:"Vietnam",color:"#bfd2c6",description:"2 cities"},
    VU:{name:"Vanuatu",color:"#7297a0",description:"0 cities"},
    YE:{name:"Yemen",color:"#8d9daf",description:"0 cities"},
    ZA:{name:"South Africa",color:"#b8d0cd",description:"0 cities"},
    ZM:{name:"Zambia",color:"#b48c8a",description:"0 cities"},
    ZW:{name:"Zimbabwe",color:"#d0b1a3",description:"0 cities"},
    SO:{name:"Somalia",color:"#a88c7d",description:"0 cities"},
    GF:{name:"France",color:"#a493b7",description:"0 cities"},
    FR:{name:"France",color:"#a089a0",description:"2 cities"},
    ES:{name:"Spain",color:"#6d6e80",description:"1 city"},
    AW:{name:"Aruba",color:"#e9dcc9",description:"0 cities"},
    AI:{name:"Anguilla",color:"#cfbeb4",description:"0 cities"},
    AD:{name:"Andorra",color:"#b1b6ba",description:"0 cities"},
    AG:{name:"Antigua and Barbuda",color:"#82ac7c",description:"0 cities"},
    BS:{name:"Bahamas",color:"#bfd2c6",description:"0 cities"},
    BM:{name:"Bermuda",color:"#7297a0",description:"0 cities"},
    BB:{name:"Barbados",color:"#8d9daf",description:"0 cities"},
    KM:{name:"Comoros",color:"#b8d0cd",description:"0 cities"},
    CV:{name:"Cape Verde",color:"#b48c8a",description:"0 cities"},
    KY:{name:"Cayman Islands",color:"#d0b1a3",description:"0 cities"},
    DM:{name:"Dominica",color:"#a88c7d",description:"0 cities"},
    FK:{name:"Falkland Islands",color:"#a493b7",description:"0 cities"},
    FO:{name:"Faeroe Islands",color:"#a089a0",description:"0 cities"},
    GD:{name:"Grenada",color:"#6d6e80",description:"0 cities"},
    HK:{name:"Hong Kong",color:"#e9dcc9",description:"0 cities"},
    KN:{name:"Saint Kitts and Nevis",color:"#cfbeb4",description:"0 cities"},
    LC:{name:"Saint Lucia",color:"#b1b6ba",description:"0 cities"},
    LI:{name:"Liechtenstein",color:"#82ac7c",description:"0 cities"},
    MF:{name:"Saint Martin (French)",color:"#bfd2c6",description:"0 cities"},
    MV:{name:"Maldives",color:"#7297a0",description:"0 cities"},
    MT:{name:"Malta",color:"#8d9daf",description:"0 cities"},
    MS:{name:"Montserrat",color:"#b8d0cd",description:"0 cities"},
    MU:{name:"Mauritius",color:"#b48c8a",description:"1 city"},
    NC:{name:"New Caledonia",color:"#d0b1a3",description:"0 cities"},
    NR:{name:"Nauru",color:"#a88c7d",description:"0 cities"},
    PN:{name:"Pitcairn Islands",color:"#a493b7",description:"0 cities"},
    PR:{name:"Puerto Rico",color:"#a089a0",description:"0 cities"},
    PF:{name:"French Polynesia",color:"#6d6e80",description:"0 cities"},
    SG:{name:"Singapore",color:"#e9dcc9",description:"1 city"},
    SB:{name:"Solomon Islands",color:"#cfbeb4",description:"0 cities"},
    ST:{name:"São Tomé and Principe",color:"#b1b6ba",description:"0 cities"},
    SX:{name:"Saint Martin (Dutch)",color:"#82ac7c",description:"0 cities"},
    SC:{name:"Seychelles",color:"#bfd2c6",description:"0 cities"},
    TC:{name:"Turks and Caicos Islands",color:"#7297a0",description:"0 cities"},
    TO:{name:"Tonga",color:"#8d9daf",description:"0 cities"},
    TT:{name:"Trinidad and Tobago",color:"#b8d0cd",description:"0 cities"},
    VC:{name:"Saint Vincent and the Grenadines",color:"#b48c8a",description:"0 cities"},
    VG:{name:"British Virgin Islands",color:"#d0b1a3",description:"0 cities"},
    VI:{name:"United States Virgin Islands",color:"#a88c7d",description:"0 cities"},
    CY:{name:"Cyprus",color:"#a493b7",description:"0 cities"},
    RE:{name:"Reunion (France)",color:"#a089a0",description:"0 cities"},
    YT:{name:"Mayotte (France)",color:"#6d6e80",description:"0 cities"},
    MQ:{name:"Martinique (France)",color:"#e9dcc9",description:"0 cities"},
    GP:{name:"Guadeloupe (France)",color:"#cfbeb4",description:"0 cities"},
    CW:{name:"Curaco (Netherlands)",color:"#b1b6ba",description:"0 cities"},
    IC:{name:"Canary Islands (Spain)",color:"#82ac7c",description:"0 cities"}
  },
  locations: {
    "0":  {name:"Beijing",         lat:39.9042, lng:116.4074, url:"https://www.metliner.com/maps/asia/beijing",          description:"Beijing, China"},
    "1":  {name:"Chongqing",       lat:29.5630, lng:106.5516, url:"https://www.metliner.com/maps/asia/chongqing",        description:"Chongqing, China"},
    "2":  {name:"Dongguan",        lat:23.0207, lng:113.7518, url:"https://www.metliner.com/maps/asia/dongguan",         description:"Dongguan, China"},
    "3":  {name:"Guangzhou",       lat:23.1291, lng:113.2644, url:"https://www.metliner.com/maps/asia/guangzhou",        description:"Guangzhou, China"},
    "4":  {name:"Harbin",          lat:45.8038, lng:126.5350, url:"https://www.metliner.com/maps/asia/harbin",           description:"Harbin, China"},
    "5":  {name:"Hong Kong",       lat:22.3193, lng:114.1694, url:"https://www.metliner.com/maps/asia/hong-kong",        description:"Hong Kong, China"},
    "6":  {name:"Macau",           lat:22.1987, lng:113.5439, url:"https://www.metliner.com/maps/asia/macau",            description:"Macau, China"},
    "7":  {name:"Shenzhen",        lat:22.5431, lng:114.0579, url:"https://www.metliner.com/maps/asia/shenzhen",         description:"Shenzhen, China"},
    "8":  {name:"Xiamen",          lat:24.4798, lng:118.0894, url:"https://www.metliner.com/maps/asia/xiamen",           description:"Xiamen, China"},
    "9":  {name:"Palembang",       lat:-2.9761, lng:104.7754, url:"https://www.metliner.com/maps/asia/palembang",        description:"Palembang, Indonesia"},
    "10": {name:"Fukuoka",         lat:33.5904, lng:130.4017, url:"https://www.metliner.com/maps/asia/fukuoka",          description:"Fukuoka, Japan"},
    "11": {name:"Hakodate",        lat:41.7688, lng:140.7290, url:"https://www.metliner.com/maps/asia/hakodate",         description:"Hakodate, Japan"},
    "12": {name:"Hiroshima",       lat:34.3853, lng:132.4553, url:"https://www.metliner.com/maps/asia/hiroshima",        description:"Hiroshima, Japan"},
    "13": {name:"Kagoshima",       lat:31.5966, lng:130.5571, url:"https://www.metliner.com/maps/asia/kagoshima",        description:"Kagoshima, Japan"},
    "14": {name:"Nagano",          lat:36.6485, lng:138.1947, url:"https://www.metliner.com/maps/asia/nagano",           description:"Nagano, Japan"},
    "15": {name:"Nagasaki",        lat:32.7503, lng:129.8777, url:"https://www.metliner.com/maps/asia/nagasaki",         description:"Nagasaki, Japan"},
    "16": {name:"Nagoya",          lat:35.1815, lng:136.9066, url:"https://www.metliner.com/maps/asia/nagoya",           description:"Nagoya, Japan"},
    "17": {name:"Naha",            lat:26.2124, lng:127.6792, url:"https://www.metliner.com/maps/asia/naha",             description:"Naha, Japan"},
    "18": {name:"Niigata",         lat:37.9026, lng:139.0232, url:"https://www.metliner.com/maps/asia/niigata",          description:"Niigata, Japan"},
    "19": {name:"Okayama",         lat:34.6551, lng:133.9195, url:"https://www.metliner.com/maps/asia/okayama",          description:"Okayama, Japan"},
    "20": {name:"Osaka",           lat:34.6937, lng:135.5023, url:"https://www.metliner.com/maps/asia/osaka",            description:"Osaka, Japan"},
    "21": {name:"Sapporo",         lat:43.0618, lng:141.3545, url:"https://www.metliner.com/maps/asia/sapporo",          description:"Sapporo, Japan"},
    "22": {name:"Sendai",          lat:38.2682, lng:140.8694, url:"https://www.metliner.com/maps/asia/sendai",           description:"Sendai, Japan"},
    "23": {name:"Tokyo",           lat:35.6762, lng:139.6503, url:"https://www.metliner.com/maps/asia/tokyo",            description:"Tokyo, Japan"},
    "24": {name:"Kuala Lumpur",    lat:3.1390,  lng:101.6869, url:"https://www.metliner.com/maps/asia/kuala-lumpur",     description:"Kuala Lumpur, Malaysia"},
    "25": {name:"Manila",          lat:14.5995, lng:120.9842, url:"https://www.metliner.com/maps/asia/manila",           description:"Manila, Philippines"},
    "26": {name:"Doha",            lat:25.2854, lng:51.5310,  url:"https://www.metliner.com/maps/asia/doha",             description:"Doha, Qatar"},
    "27": {name:"Singapore",       lat:1.3521,  lng:103.8198, url:"https://www.metliner.com/maps/asia/singapore",        description:"Singapore"},
    "28": {name:"Busan",           lat:35.1796, lng:129.0756, url:"https://www.metliner.com/maps/asia/busan",            description:"Busan, South Korea"},
    "29": {name:"Daegu",           lat:35.8714, lng:128.6014, url:"https://www.metliner.com/maps/asia/daegu",            description:"Daegu, South Korea"},
    "30": {name:"Daejeon",         lat:36.3504, lng:127.3845, url:"https://www.metliner.com/maps/asia/daejeon",          description:"Daejeon, South Korea"},
    "31": {name:"Gwangju",         lat:35.1595, lng:126.8526, url:"https://www.metliner.com/maps/asia/gwangju",          description:"Gwangju, South Korea"},
    "32": {name:"Seoul",           lat:37.5665, lng:126.9780, url:"https://www.metliner.com/maps/asia/seoul",            description:"Seoul, South Korea"},
    "33": {name:"Kaohsiung",       lat:22.6273, lng:120.3014, url:"https://www.metliner.com/maps/asia/kaohsiung",        description:"Kaohsiung, Taiwan"},
    "34": {name:"Taichung",        lat:24.1477, lng:120.6736, url:"https://www.metliner.com/maps/asia/taichung",         description:"Taichung, Taiwan"},
    "35": {name:"Taipei",          lat:25.0330, lng:121.5654, url:"https://www.metliner.com/maps/asia/taipei",           description:"Taipei, Taiwan"},
    "36": {name:"Bangkok",         lat:13.7563, lng:100.5018, url:"https://www.metliner.com/maps/asia/bangkok",          description:"Bangkok, Thailand"},
    "37": {name:"Dubai",           lat:25.2048, lng:55.2708,  url:"https://www.metliner.com/maps/asia/dubai",            description:"Dubai, UAE"},
    "38": {name:"Hanoi",           lat:21.0285, lng:105.8542, url:"https://www.metliner.com/maps/asia/hanoi",            description:"Hanoi, Vietnam"},
    "39": {name:"Ho Chi Minh City",lat:10.8231, lng:106.6297, url:"https://www.metliner.com/maps/asia/ho-chi-minh-city", description:"Ho Chi Minh City, Vietnam"}
  },
  labels: {},
  legend: {entries: []},
  regions: {
    "0": {name:"Oceania", states:["AU","FJ","GU","MH","NZ","PW","WS","SB","TK","PG"], color:"#ff0025"},
    "1": {name:"America", states:["AI","AR","AW","BB","BZ","BM","BO","BR","KY","CL","CO","CR","PA","PY","PE","KN","DO","DM","EC","SV","GD","GT","GY","HA","HN","JM","LC","VC","SR","TT","UY","VE","NI","CU","HT","AG","GF","US","MX","CA","BS","PR"], color:"#ee334e"},
    "2": {name:"Europe",  states:["AL","AD","AT","BY","BE","BA","BV","BG","HR","CY","CZ","DK","EE","FO","FK","FI","FR","TF","DE","GI","GR","GL","GG","VA","HU","IS","IE","IM","IT","JE","LV","LI","LT","LU","MK","MT","MD","MC","NL","NO","PL","PT","RO","RU","SM","RS","ME","XK","SK","SI","ES","SJ","SE","CH","UA","GB","TR"], color:"#0081c8"},
    "3": {name:"Africa",  states:["DZ","AO","BJ","BW","BF","BI","CM","CV","CF","TD","CG","CI","MG","MW","ML","MU","MR","MA","NA","NE","NG","CD","EG","ER","ET","GA","GH","GN","LS","ST","SN","SC","SL","SO","ZA","SZ","TZ","TG","TN","UG","ZM","ZW","LY","SD","SS","KE","MZ","RW","LR","GW","EH"], color:"#000000"},
    "5": {name:"Asia",    states:["AF","AM","AZ","BH","BD","BT","BN","KH","CN","TL","GE","HK","IN","ID","IR","IQ","IL","JP","JO","KZ","KP","KR","KW","KG","LA","LB","MO","MY","MN","MM","NP","OM","PK","PH","QA","SA","SG","LK","SY","TW","TJ","TH","TM","AE","UZ","VN","YE"], color:"#fcb131"}
  }
};
